config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/teachers/new', to: 'teachers#new'
  post '/teachers', to: 'teachers#create'
  get '/students/new', to: 'students#new'
  post '/students', to: 'students#create'
  get '', to: redirect('/students/new')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @Hometown = 'California'
    @Hobby='Sleeping'
    @Name='rob'
  end

  def create
    # Hint: params??
    @Name = params[:Name]
    @Hometown=params[:Hometown]
    @Hobby=params[:Hobby]
    render 'show'
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new
    @placeholder_course = '186'
  end

  def create
    # Hint: params??
    @full_name = params[:full_name]
    @course=params[:course_name]
    @grade_level=params[:grade_level]
    render 'show'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fa17Hw3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/new.html.erb
<%= form_tag students_path do |post| %>
  <%= label_tag(:Name, "Name") %>
  <%= text_field_tag(:Name, nil, placeholder: @Name) %>

  <%= label_tag(:Hometown, "Hometown") %>
  <%= text_field_tag(:Hometown, nil, placeholder: @Hometown) %>

  <%= label_tag(:Hobby, "Hobby") %>
  <%= text_field_tag(:Hobby, nil, placeholder: @Hobby) %>

  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <%= submit_tag("Create student") %>
<% end %>

app/views/students/show.html.erb
<div>
  <h2>Your form inputs for student</h2>
  <h4>Name</h4>
  <h3>
    <%= @Name %>
  </h3>
  <h4>Hometown</h4>
  <h3>
    <%= @Hometown %>
  </h3>
  <h4>Hobby</h4>
  <h3>
    <%= @Hobby %>
  </h3>
</div>

app/views/teachers/new.html.erb
<%= form_tag teachers_path do |post| %>
  <%= label_tag(:full_name, "Full name") %>
  <%= text_field_tag(:full_name) %>

  <%= label_tag(:course_name, "Course name") %>
  <%= text_field_tag(:course_name, nil, placeholder: @placeholder_course) %>

  <%= label_tag(:grade_level, "Grade level") %>
  <%= text_field_tag(:grade_level) %>

  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <%= submit_tag("Create teacher") %>
<% end %>

<!--
NOTE: The form above is exactly identical to the below HTML form. It purely uses rails helper methods to create the form. Take some time to understand you can utilize the rails helper methods to customize forms juast as you would normal HTML forms. :)

<form action="/teachers" method="POST">
  <label>Full name</label>
  <input name="full_name" type="text"></input>
  <label>Course name</label>
  <input
    name="course"
    placeholder=<%= @placeholder_course %>
    type="text"
  >
  </input>
  <label>Grade level</label>
  <input name="grade_level" type="text"></input>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <button type="submit">Create teacher</button>
</form>
-->

app/views/teachers/show.html.erb
<div>
  <h2>Your form inputs</h2>
  <h4>Full name</h4>
  <h3>
    <%= @full_name %>
  </h3>
  <h4>Course</h4>
  <h3>
    <%= @course %>
  </h3>
  <h4>Grade level</h4>
  <h3>
    <%= @grade_level %>
  </h3>
</div>